plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

layout.buildDirectory = layout.projectDirectory.dir('build/gradle')

repositories {
}

loom {
    splitEnvironmentSourceSets()

    mods {
        craftmetry {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

configurations {
    productionRuntimeMods {
        canBeConsumed = false
        canBeResolved = true
        transitive = false
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    productionRuntimeMods "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property 'archivesName', project.base.archivesName

    from('LICENSE') {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

tasks.register('runProductionClient', net.fabricmc.loom.task.prod.ClientProductionRunTask) {
    dependsOn tasks.named('jar')
    mods.from tasks.named('jar')
    mods.from configurations.productionRuntimeMods
    runDir = file('run-production')
    jvmArgs.add '-Xdock:name=Craftmetry'
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
